# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.hostname = "hvbench"
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.0.0.2"

  config.vm.provision :shell, path: "provision_root.sh"
  config.vm.provision :shell, path: "provision.sh", privileged: false

  config.vm.synced_folder "../", "/hvbench"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

end

